default_config = {
    "vmc.outer_sample_size": 10_000,
    "vmc.inner_sample_size": 10_000,
    "vmc.inner_epochs": 1,
    "vmc.max_steps": 15000,
    "vmc.lr": 1e-3,
    "vmc.batch_size": 10000,
    "vmc.weight_decay": 0,
    "vmc.eval_set_max_size": 50000,
    "vmc.device": "auto",
    "system.lattice": "kagome2x4",
    "system.J2": 1,
    "system.symmetry_basis": None,
    "system.spin_inversion": None,
    "random_seed": None,
    "log_prob_fn": "invariant_cnn",
    "log_prob_fn.invariant_cnn.dilations": None,
    "log_prob_fn.invariant_cnn.hidden_channels": None,
    "log_prob_fn.invariant_cnn.kernel_size": None,
    "warm_up": "vmc_true_signs",
    "warm_up.vmc_true_signs.overlap": 0.7,
    "warm_up.vmc_true_signs.max_steps": None,
    "sign_reconstruction": "annealing",
    "sign_reconstruction.update_each_outer_steps": 1,  # should be 1
    #                                                    unless sign_reconstruction.hadamard_spread is True
    "sign_reconstruction.annealing.number_sweeps": 100,
    "sign_reconstruction.annealing.repetitions": 18,
    "sign_reconstruction.extension_steps": None,
    "sign_reconstruction.full_spin_regularization": None,
    "sign_reconstruction.hadamard_spread": False,
    "runs": 1,
    "log_prob_fn.split_group_res_conv_net.extend_filter1": None,
    "log_prob_fn.split_group_res_conv_net.filter_size": None,
    "log_prob_fn.split_group_res_conv_net.channels": None,
    "log_prob_fn.split_group_res_conv_net.res_blocks": None,
    "log_prob_fn.split_group_res_conv_net.additional_generators": None,
    "log_prob_fn.invariant_res_cnn.resnet_blocks": None,
    "log_prob_fn.invariant_res_cnn.resnet_block_depth": None,
    "log_prob_fn.invariant_res_cnn.hidden_channels": None,
}

configs = {
    0: {
        "system.lattice": "kagome2x4",
        "system.J2": 0.99,
        "system.symmetry_basis": "zero_sector",
        "log_prob_fn.invariant_cnn.hidden_channels": [32, 32, 32],
        "log_prob_fn.invariant_cnn.kernel_size": 2,
        "warm_up.vmc_true_signs.overlap": 0.7,
        "sign_reconstruction.extension_steps": 1,
        "sign_reconstruction": "greedy_solve",
        "vmc.outer_sample_size": 100_000,
        "vmc.inner_sample_size": 10_000,
        "vmc.inner_epochs": 10,
    },
    1: {
        "_inherit": 0,
        "warm_up.vmc_true_signs.overlap": 0.6,
    },
    2: {
        "_inherit": 0,
        "system.lattice": "kagome3x3",
        "log_prob_fn": "invariant_res_cnn",
        "log_prob_fn.invariant_res_cnn.resnet_blocks": 4,
        "log_prob_fn.invariant_res_cnn.resnet_block_depth": 1,
        "log_prob_fn.invariant_res_cnn.hidden_channels": 64,
    },
    3: {
        "_inherit": 2,
        "sign_reconstruction.extension_steps": 2,
    },
    4: {
        "_inherit": 0,
        "system.lattice": "kagome36round",
        "system.J2": None,
        "system.spin_inversion": 1,
        "vmc.max_steps": 50000,
        "log_prob_fn": "split_group_res_conv_net",
        "log_prob_fn.split_group_res_conv_net.additional_generators": [
            "rotation",
            "flip",
        ],
        "log_prob_fn.split_group_res_conv_net.extend_filter1": (1, 1),
        "log_prob_fn.split_group_res_conv_net.filter_size": (2, 2),
        "log_prob_fn.split_group_res_conv_net.channels": 16,
        "log_prob_fn.split_group_res_conv_net.res_blocks": 4,
        "warm_up.vmc_true_signs.overlap": 0.7,
        "vmc.outer_sample_size": 50_000,
        "vmc.inner_sample_size": 10_000,
    },
    5: {
        "_inherit": 4,
        "vmc.outer_sample_size": 20_000,
        "vmc.inner_sample_size": 4_000,
    },
    6: {
        "_inherit": 4,
        "vmc.outer_sample_size": 100_000,
        "vmc.inner_sample_size": 10_000,
    },
    7: {"_inherit": 4, "sign_reconstruction.extension_steps": 2},
    8: {"_inherit": 7, "vmc.outer_sample_size": 10_000, "vmc.inner_sample_size": 1000},
    9: {
        "system.lattice": "kagome2x4",
        "system.J2": 0.99,
        "system.symmetry_basis": "zero_sector",
        "log_prob_fn.invariant_cnn.hidden_channels": [32, 32, 32],
        "log_prob_fn.invariant_cnn.kernel_size": 2,
        "warm_up.vmc_true_signs.overlap": 0.7,
        "sign_reconstruction.extension_steps": 1,
        "sign_reconstruction": "greedy_solve",
        "vmc.outer_sample_size": 10_000,
        "vmc.inner_sample_size": 10_000,
        "vmc.inner_epochs": 1,
    },
    10: {
        "_inherit": 9,
        "sign_reconstruction.extension_steps": 2,
    },
    11: {
        "_inherit": 10,
        "sign_reconstruction.update_each_outer_steps": 10,
        "sign_reconstruction.hadamard_spread": True,
    },
    12: {
        "_inherit": 11,
        "sign_reconstruction.update_each_outer_steps": 100,
    },
}
